# Generated by Django 5.2.8 on 2026-07-16 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدولة')),
                ('flag_icon', models.CharField(default='🏳️', max_length=50, verbose_name='أيقونة العلم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('marketing', 'تسويق وإعلانات'), ('tools', 'أدوات وتراخيص'), ('teachers_related', 'مصروفات متعلقة بالمعلمات'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المعلمة')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='السن')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='واتساب')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ القبض')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'معلمة',
                'verbose_name_plural': 'المعلمات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='السن')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الباقة')),
                ('lessons_count', models.PositiveIntegerField(default=4, verbose_name='عدد الحلقات')),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الاشتراك')),
                ('month', models.CharField(max_length=20, verbose_name='الشهر')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية الاشتراك')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الاشتراك')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='آخر دفعة')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('pending', 'مستحق'), ('overdue', 'متأخر')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('status', models.CharField(choices=[('active', 'مقيد'), ('inactive', 'غير مقيد')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('enrollment_type', models.CharField(choices=[('new', 'طالب جديد'), ('existing', 'طالب مسجل من قبل')], default='new', max_length=20, verbose_name='نوع التسجيل')),
                ('acquisition_source', models.CharField(blank=True, choices=[('ad', 'إعلان'), ('referral', 'توصية'), ('website', 'الموقع'), ('social_media', 'سوشيال ميديا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='مصدر الطالب (لو جديد)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.country', verbose_name='الدولة')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.teacher', verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='نص الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='أضيف بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_timeline', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملاحظة طالب',
                'verbose_name_plural': 'سجل الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
    ]
