# Generated by Django 5.2.8 on 2025-11-16 19:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المعلم')),
                ('job_title', models.CharField(choices=[('junior', 'معلم مبتدئ'), ('intermediate', 'معلم متوسط'), ('senior', 'معلم خبير'), ('master', 'معلم متميز')], default='junior', max_length=20, verbose_name='الوظيفة')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الشهري')),
                ('working_hours', models.PositiveIntegerField(default=0, verbose_name='عدد ساعات العمل')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مكافآت')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصومات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعيين')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('session_duration', models.PositiveIntegerField(choices=[(30, '30 دقيقة'), (40, '40 دقيقة'), (60, '60 دقيقة')], default=30, verbose_name='مدة الحلقة')),
                ('lessons_count', models.PositiveIntegerField(choices=[(4, '4 حلقات'), (6, '6 حلقات'), (8, '8 حلقات'), (12, '12 حلقة'), (16, '16 حلقة')], default=4, verbose_name='عدد الحلقات')),
                ('payment_type', models.CharField(choices=[('monthly', 'شهري'), ('per_lesson', 'حسب الحلقة')], default='monthly', max_length=20, verbose_name='نظام الدفع')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المدفوع')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.teacher', verbose_name='المعلم')),
            ],
        ),
    ]
