# Generated by Django 5.2.8 on 2026-07-17 00:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='نسبة المعلمة من الاشتراكات (%)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='راتب مثبت (بدل النسبة)'),
        ),
        migrations.CreateModel(
            name='TeacherSalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الصرف')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي (محسوب وقت الصرف)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات')),
                ('leave_days', models.PositiveIntegerField(default=0, verbose_name='عدد أيام الإجازة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='core.teacher', verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'سجل راتب',
                'verbose_name_plural': 'سجل الرواتب',
                'ordering': ['-payout_date', '-created_at'],
            },
        ),
    ]
