# Generated by Django 5.2.8 on 2026-07-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='نسبة المعلمة من الاشتراكات (%)'),
        ),
    ]
