# Generated by Django 5.2.8 on 2026-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_commission_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='commission_percent',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'إيجار'), ('marketing', 'تسويق وإعلانات'), ('tools', 'أدوات وتراخيص'), ('teachers_related', 'مصروفات متعلقة بالمعلمات'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='التصنيف'),
        ),
    ]
