# Generated by Django 5.2.8 on 2026-07-20 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_teacher_bonus_remove_teacher_deduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز المشاركة العام')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المعلمة')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الباقة')),
                ('lessons_count', models.PositiveIntegerField(default=4, verbose_name='عدد الحلقات')),
                ('month_label', models.CharField(max_length=30, verbose_name='الشهر')),
                ('memorization_progress', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار حفظ الجديد')),
                ('review_progress', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار المراجعة')),
                ('absences', models.CharField(blank=True, max_length=255, null=True, verbose_name='عدد مرات الغياب')),
                ('pronunciation_rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='النطق ومخارج الحروف')),
                ('tajweed_rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='تطبيق أحكام التجويد')),
                ('interaction_rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='التفاعل مع المعلمة')),
                ('response_speed_rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='سرعة الاستجابة والحفظ')),
                ('commitment_rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='الالتزام بالمواعيد والآداب')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='التوصيات / المستوى العام')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='كلمة المعلمة')),
                ('month_rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='مستوى الشهر')),
                ('template', models.CharField(choices=[('teal_pink', 'تركواز ووردي'), ('violet', 'بنفسجي (هوية المنصة)'), ('sunny', 'أصفر وبرتقالي دافئ')], default='teal_pink', max_length=20, verbose_name='شكل النموذج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقييم شهري',
                'verbose_name_plural': 'التقييمات الشهرية',
                'ordering': ['-created_at'],
            },
        ),
    ]
