# Generated by Django 6.1 on 2026-08-11 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monthlyevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='موعد الحلقة')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدة الحلقة (دقيقة)')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'تمت'), ('student_absent', 'الطالب غائب'), ('teacher_absent', 'المعلمة لم تتمكن من الحضور'), ('cancelled', 'أُلغيت'), ('unregistered', 'غير مسجلة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('status_recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الحالة')),
                ('auto_flagged', models.BooleanField(default=False, verbose_name='اتعلّمت غير مسجلة تلقائيًا')),
                ('was_late', models.BooleanField(default=False, verbose_name='اتأخرت المعلمة في الحضور')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات على الحلقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.student', verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.teacher', verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'حلقة',
                'verbose_name_plural': 'الحلقات',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new', 'موعد جديد'), ('change', 'تعديل موعد قائم')], default='new', max_length=10, verbose_name='نوع الطلب')),
                ('proposed_days', models.CharField(blank=True, max_length=150, null=True, verbose_name='الأيام المقترحة')),
                ('proposed_time', models.TimeField(blank=True, null=True, verbose_name='الوقت المقترح')),
                ('proposed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='الموعد المقترح (لتعديل حلقة بعينها)')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('teacher_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة المعلمة')),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('related_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='core.lesson', verbose_name='الحلقة المطلوب تعديلها (لو تعديل)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to='core.student', verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to='core.teacher', verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'طلب موعد',
                'verbose_name_plural': 'طلبات المواعيد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='تفاصيل الشكوى')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.teacher', verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'شكوى على معلمة',
                'verbose_name_plural': 'شكاوى المعلمات',
                'ordering': ['-date'],
            },
        ),
    ]
