# Generated by Django 5.2.8 on 2026-07-15 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='شغالة حاليًا'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ ترك العمل'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_percentage',
            field=models.DecimalField(decimal_places=2, default=70, help_text='نسبة المعلمة من إجمالي اشتراكات طالباتها كل شهر (الباقي بيبقى نسبة المنصة)', max_digits=5, verbose_name='نسبة المعلمة %'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغ ثابت شهري بيتضاف فوق نسبتها من الاشتراكات (سيبيه صفر لو مفيش)', max_digits=10, verbose_name='راتب ثابت إضافي'),
        ),
        migrations.CreateModel(
            name='TeacherMonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي اشتراكات طالباتها هذا الشهر')),
                ('teacher_percentage', models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='نسبة المعلمة المستخدمة')),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الثابت المستخدم')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت المستخدمة')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات المستخدمة')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفول')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القفل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to='core.teacher', verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'سجل شهري للمعلمة',
                'verbose_name_plural': 'السجلات الشهرية للمعلمات',
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
    ]
