# Generated by Django 6.1 on 2026-08-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_schedulerequest_teachercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل'),
        ),
    ]
