# Generated by Django 5.2.8 on 2026-07-16 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher_is_active_teacher_join_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='leave_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_percentage',
        ),
        migrations.AddField(
            model_name='student',
            name='acquisition_source',
            field=models.CharField(blank=True, choices=[('ad', 'إعلان'), ('referral', 'توصية'), ('website', 'الموقع'), ('social_media', 'سوشيال ميديا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='مصدر الطالب (لو جديد)'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_type',
            field=models.CharField(choices=[('new', 'طالب جديد'), ('existing', 'طالب مسجل من قبل')], default='new', max_length=20, verbose_name='نوع التسجيل'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TeacherMonthlyRecord',
        ),
    ]
