# Generated by Django 6.1 on 2026-08-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الحلقة فعليًا'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='auto_flagged',
            field=models.BooleanField(default=False, verbose_name='اتحسبت غياب تلقائيًا من غير ما تتسجل'),
        ),
    ]
