# Generated by Django 5.2.8 on 2026-02-08 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='الاسم يجب أن يكون حرفين على الأقل')], verbose_name='الاسم')),
                ('visitor_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('visitor_phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('title', models.CharField(help_text='عنوان واضح ومختصر للسؤال', max_length=200, validators=[django.core.validators.MinLengthValidator(10, message='العنوان يجب أن يكون 10 أحرف على الأقل')], verbose_name='عنوان السؤال')),
                ('question_text', models.TextField(help_text='اشرح سؤالك بالتفصيل', validators=[django.core.validators.MinLengthValidator(20, message='السؤال يجب أن يكون 20 حرف على الأقل')], verbose_name='تفاصيل السؤال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح الزائر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('status', models.CharField(choices=[('pending', '⏳ قيد المراجعة'), ('approved', '✅ معتمد ونشر'), ('rejected', '❌ مرفوض'), ('spam', '🚫 سبام')], db_index=True, default='pending', max_length=10, verbose_name='حالة السؤال')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('is_frequent', models.BooleanField(default=False, verbose_name='سؤال متكرر')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='رابط السؤال')),
                ('meta_description', models.TextField(blank=True, help_text='وصف مختصر يظهر في نتائج محركات البحث', max_length=160, verbose_name='وصف للبحث')),
            ],
            options={
                'verbose_name': 'سؤال عام',
                'verbose_name_plural': 'الأسئلة العامة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فئة الأسئلة',
                'verbose_name_plural': 'فئات الأسئلة',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(validators=[django.core.validators.MinLengthValidator(20, message='الإجابة يجب أن تكون 20 حرف على الأقل')], verbose_name='نص الإجابة')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجابة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_featured', models.BooleanField(default=False, verbose_name='إجابة مميزة')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='الإعجابات')),
                ('answered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أجاب بواسطة')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_answer', to='qna.publicquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة رسمية',
                'verbose_name_plural': 'الإجابات الرسمية',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.AddField(
            model_name='publicquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qna.questioncategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التصويت')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qna.questionanswer', verbose_name='الإجابة')),
            ],
            options={
                'verbose_name': 'تصويت',
                'verbose_name_plural': 'التصويتات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicquestion',
            index=models.Index(fields=['-created_at'], name='qna_publicq_created_4c8093_idx'),
        ),
        migrations.AddIndex(
            model_name='publicquestion',
            index=models.Index(fields=['status', '-created_at'], name='qna_publicq_status_0fb56b_idx'),
        ),
        migrations.AddIndex(
            model_name='publicquestion',
            index=models.Index(fields=['slug'], name='qna_publicq_slug_d98ece_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('answer', 'ip_address')},
        ),
    ]
