# Generated by Django 5.2.8 on 2026-02-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicquestion',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='رابط السؤال'),
        ),
    ]
