# Generated by Django 5.2.8 on 2026-02-08 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_alter_publicquestion_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservote',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصويت رسمي', 'verbose_name_plural': 'التصويتات الرسمية'},
        ),
        migrations.CreateModel(
            name='CommunityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='اكتب إجابتك بالتفصيل', validators=[django.core.validators.MinLengthValidator(20, message='الإجابة يجب أن تكون 20 حرف على الأقل')], verbose_name='نص الإجابة')),
                ('visitor_name', models.CharField(blank=True, help_text='اكتب اسمك إذا لم تكن مسجلاً', max_length=100, verbose_name='اسم الزائر')),
                ('visitor_email', models.EmailField(blank=True, help_text='اختياري - للإشعارات', max_length=254, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('is_spam', models.BooleanField(default=False, verbose_name='محتوى غير مرغوب')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='الإعجابات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_answers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.publicquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة المجتمع',
                'verbose_name_plural': 'إجابات المجتمع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityAnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التصويت')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qna.communityanswer', verbose_name='إجابة المجتمع')),
            ],
            options={
                'verbose_name': 'تصويت مجتمعي',
                'verbose_name_plural': 'التصويتات المجتمعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'محتوى ترويجي'), ('inappropriate', 'محتوى غير لائق'), ('incorrect', 'معلومات غير صحيحة'), ('duplicate', 'سؤال مكرر'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإبلاغ')),
                ('description', models.TextField(help_text='اشرح سبب الإبلاغ', verbose_name='تفاصيل الإبلاغ')),
                ('reporter_ip', models.GenericIPAddressField(verbose_name='عنوان IP المبلغ')),
                ('reporter_email', models.EmailField(blank=True, help_text='اختياري - للتواصل معك', max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='qna.communityanswer', verbose_name='الإجابة (إذا كان الإبلاغ عليها)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='qna.publicquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إبلاغ',
                'verbose_name_plural': 'الإبلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='للتسجيل بدون حساب', max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='qna.publicquestion', verbose_name='السؤال')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.AddIndex(
            model_name='communityanswer',
            index=models.Index(fields=['question', '-created_at'], name='qna_communi_questio_227ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='communityanswer',
            index=models.Index(fields=['is_verified', '-created_at'], name='qna_communi_is_veri_f0ec6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communityanswervote',
            unique_together={('answer', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='questionsubscription',
            unique_together={('question', 'email'), ('question', 'user')},
        ),
    ]
